// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkzgxdmnvyoviwketxva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhremd4ZG1udnlvdml3a2V0eHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjUzNzUsImV4cCI6MjA2NjgwMTM3NX0.roSANiwzCTmjsDCsVBnHg6c1mr1XKpWXpopFcDaIdrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});